name = "ai-chat-backend"
main = "worker.js"
compatibility_date = "2024-06-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "ChatRoomDurableObject" ]

[[d1_databases]]
binding = "ROOM_DB"
database_name = "family_chat_db"
database_id = "66744845-057c-459b-98a1-fefaf2659752"